// @generated by protoc-gen-connect-es v1.5.0
// @generated from file ticketquerier/v1/service.proto (package ticketquerier.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTicketByIdRequest, GetTicketByIdResponse, QueryTicketsRequest, QueryTicketsResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ticketquerier.v1.TicketQuerierService
 */
export declare const TicketQuerierService: {
  readonly typeName: "ticketquerier.v1.TicketQuerierService",
  readonly methods: {
    /**
     * @generated from rpc ticketquerier.v1.TicketQuerierService.QueryTickets
     */
    readonly queryTickets: {
      readonly name: "QueryTickets",
      readonly I: typeof QueryTicketsRequest,
      readonly O: typeof QueryTicketsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ticketquerier.v1.TicketQuerierService.GetTicketById
     */
    readonly getTicketById: {
      readonly name: "GetTicketById",
      readonly I: typeof GetTicketByIdRequest,
      readonly O: typeof GetTicketByIdResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

