// @generated by protoc-gen-es v1.10.0
// @generated from file ticketquerier/v1/service.proto (package ticketquerier.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message ticketquerier.v1.Ticket
 */
export const Ticket = /*@__PURE__*/ proto3.makeMessageType(
  "ticketquerier.v1.Ticket",
  () => [
    { no: 1, name: "ticket_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "created_at", kind: "message", T: Timestamp },
    { no: 3, name: "updated_at", kind: "message", T: Timestamp },
    { no: 4, name: "created_by", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "deadline", kind: "message", T: Timestamp },
  ],
);

/**
 * @generated from message ticketquerier.v1.QueryTicketsRequest
 */
export const QueryTicketsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "ticketquerier.v1.QueryTicketsRequest",
  () => [
    { no: 1, name: "requested_by", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message ticketquerier.v1.QueryTicketsResponse
 */
export const QueryTicketsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "ticketquerier.v1.QueryTicketsResponse",
  () => [
    { no: 1, name: "tickets", kind: "message", T: Ticket, repeated: true },
  ],
);

/**
 * @generated from message ticketquerier.v1.GetTicketByIdRequest
 */
export const GetTicketByIdRequest = /*@__PURE__*/ proto3.makeMessageType(
  "ticketquerier.v1.GetTicketByIdRequest",
  () => [
    { no: 1, name: "ticket_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message ticketquerier.v1.GetTicketByIdResponse
 */
export const GetTicketByIdResponse = /*@__PURE__*/ proto3.makeMessageType(
  "ticketquerier.v1.GetTicketByIdResponse",
  () => [
    { no: 1, name: "ticket", kind: "message", T: Ticket },
  ],
);

