// @generated by protoc-gen-es v2.2.3
// @generated from file accountmgr/v1/service.proto (package accountmgr.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file accountmgr/v1/service.proto.
 */
export declare const file_accountmgr_v1_service: GenFile;

/**
 * @generated from message accountmgr.v1.SlackSSORequest
 */
export declare type SlackSSORequest = Message<"accountmgr.v1.SlackSSORequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string slack_user_id = 3;
   */
  slackUserId: string;

  /**
   * @generated from field: string slack_team_id = 4;
   */
  slackTeamId: string;
};

/**
 * Describes the message accountmgr.v1.SlackSSORequest.
 * Use `create(SlackSSORequestSchema)` to create a new message.
 */
export declare const SlackSSORequestSchema: GenMessage<SlackSSORequest>;

/**
 * @generated from message accountmgr.v1.SlackSSOResponse
 */
export declare type SlackSSOResponse = Message<"accountmgr.v1.SlackSSOResponse"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message accountmgr.v1.SlackSSOResponse.
 * Use `create(SlackSSOResponseSchema)` to create a new message.
 */
export declare const SlackSSOResponseSchema: GenMessage<SlackSSOResponse>;

/**
 * @generated from service accountmgr.v1.AccountMgrService
 */
export declare const AccountMgrService: GenService<{
  /**
   * @generated from rpc accountmgr.v1.AccountMgrService.SlackSSO
   */
  slackSSO: {
    methodKind: "unary";
    input: typeof SlackSSORequestSchema;
    output: typeof SlackSSOResponseSchema;
  },
}>;

