// @generated by protoc-gen-connect-es v1.5.0
// @generated from file todomgr/v1/service.proto (package todomgr.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateTicketRequest, CreateTicketResponse, DeleteTicketRequest, DeleteTicketResponse, UpdateTicketRequest, UpdateTicketResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service todomgr.v1.TicketMgrService
 */
export const TicketMgrService = {
  typeName: "todomgr.v1.TicketMgrService",
  methods: {
    /**
     * @generated from rpc todomgr.v1.TicketMgrService.CreateTicket
     */
    createTicket: {
      name: "CreateTicket",
      I: CreateTicketRequest,
      O: CreateTicketResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc todomgr.v1.TicketMgrService.UpdateTicket
     */
    updateTicket: {
      name: "UpdateTicket",
      I: UpdateTicketRequest,
      O: UpdateTicketResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc todomgr.v1.TicketMgrService.DeleteTicket
     */
    deleteTicket: {
      name: "DeleteTicket",
      I: DeleteTicketRequest,
      O: DeleteTicketResponse,
      kind: MethodKind.Unary,
    },
  }
};

