// @generated by protoc-gen-es v1.10.0
// @generated from file accountmgr/v1/service.proto (package accountmgr.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message accountmgr.v1.SlackSSORequest
 */
export declare class SlackSSORequest extends Message<SlackSSORequest> {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string slack_user_id = 3;
   */
  slackUserId: string;

  /**
   * @generated from field: string slack_team_id = 4;
   */
  slackTeamId: string;

  constructor(data?: PartialMessage<SlackSSORequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "accountmgr.v1.SlackSSORequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SlackSSORequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SlackSSORequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SlackSSORequest;

  static equals(a: SlackSSORequest | PlainMessage<SlackSSORequest> | undefined, b: SlackSSORequest | PlainMessage<SlackSSORequest> | undefined): boolean;
}

/**
 * @generated from message accountmgr.v1.SlackSSOResponse
 */
export declare class SlackSSOResponse extends Message<SlackSSOResponse> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  constructor(data?: PartialMessage<SlackSSOResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "accountmgr.v1.SlackSSOResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SlackSSOResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SlackSSOResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SlackSSOResponse;

  static equals(a: SlackSSOResponse | PlainMessage<SlackSSOResponse> | undefined, b: SlackSSOResponse | PlainMessage<SlackSSOResponse> | undefined): boolean;
}

