// @generated by protoc-gen-es v1.10.0
// @generated from file accountmgr/v1/service.proto (package accountmgr.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message accountmgr.v1.SlackSSORequest
 */
export const SlackSSORequest = /*@__PURE__*/ proto3.makeMessageType(
  "accountmgr.v1.SlackSSORequest",
  () => [
    { no: 1, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "slack_user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "slack_team_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message accountmgr.v1.SlackSSOResponse
 */
export const SlackSSOResponse = /*@__PURE__*/ proto3.makeMessageType(
  "accountmgr.v1.SlackSSOResponse",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

