// @generated by protoc-gen-es v2.2.3
// @generated from file accountmgr/v1/service.proto (package accountmgr.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file accountmgr/v1/service.proto.
 */
export const file_accountmgr_v1_service = /*@__PURE__*/
  fileDesc("ChthY2NvdW50bWdyL3YxL3NlcnZpY2UucHJvdG8SDWFjY291bnRtZ3IudjEiXAoPU2xhY2tTU09SZXF1ZXN0Eg0KBWVtYWlsGAEgASgJEgwKBG5hbWUYAiABKAkSFQoNc2xhY2tfdXNlcl9pZBgDIAEoCRIVCg1zbGFja190ZWFtX2lkGAQgASgJIiMKEFNsYWNrU1NPUmVzcG9uc2USDwoHdXNlcl9pZBgBIAEoCTJiChFBY2NvdW50TWdyU2VydmljZRJNCghTbGFja1NTTxIeLmFjY291bnRtZ3IudjEuU2xhY2tTU09SZXF1ZXN0Gh8uYWNjb3VudG1nci52MS5TbGFja1NTT1Jlc3BvbnNlIgBCvAEKEWNvbS5hY2NvdW50bWdyLnYxQgxTZXJ2aWNlUHJvdG9QAVpEZ2l0aHViLmNvbS90LWFzaDA0MTAvc3RhY2stZXhhbXBsZS9nby9hcGkvYWNjb3VudG1nci92MTthY2NvdW50bWdydjGiAgNBWFiqAg1BY2NvdW50bWdyLlYxygINQWNjb3VudG1nclxWMeICGUFjY291bnRtZ3JcVjFcR1BCTWV0YWRhdGHqAg5BY2NvdW50bWdyOjpWMWIGcHJvdG8z");

/**
 * Describes the message accountmgr.v1.SlackSSORequest.
 * Use `create(SlackSSORequestSchema)` to create a new message.
 */
export const SlackSSORequestSchema = /*@__PURE__*/
  messageDesc(file_accountmgr_v1_service, 0);

/**
 * Describes the message accountmgr.v1.SlackSSOResponse.
 * Use `create(SlackSSOResponseSchema)` to create a new message.
 */
export const SlackSSOResponseSchema = /*@__PURE__*/
  messageDesc(file_accountmgr_v1_service, 1);

/**
 * @generated from service accountmgr.v1.AccountMgrService
 */
export const AccountMgrService = /*@__PURE__*/
  serviceDesc(file_accountmgr_v1_service, 0);

