// @generated by protoc-gen-connect-es v1.6.1
// @generated from file ticketquerier/v1/service.proto (package ticketquerier.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTicketByIdRequest, GetTicketByIdResponse, QueryTicketsRequest, QueryTicketsResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ticketquerier.v1.TicketQuerierService
 */
export const TicketQuerierService = {
  typeName: "ticketquerier.v1.TicketQuerierService",
  methods: {
    /**
     * @generated from rpc ticketquerier.v1.TicketQuerierService.QueryTickets
     */
    queryTickets: {
      name: "QueryTickets",
      I: QueryTicketsRequest,
      O: QueryTicketsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ticketquerier.v1.TicketQuerierService.GetTicketById
     */
    getTicketById: {
      name: "GetTicketById",
      I: GetTicketByIdRequest,
      O: GetTicketByIdResponse,
      kind: MethodKind.Unary,
    },
  }
};

