// @generated by protoc-gen-es v1.10.0
// @generated from file ticketmgr/v1/service.proto (package ticketmgr.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message ticketmgr.v1.CreateTicketRequest
 */
export const CreateTicketRequest = /*@__PURE__*/ proto3.makeMessageType(
  "ticketmgr.v1.CreateTicketRequest",
  () => [
    { no: 1, name: "requested_by", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "deadline", kind: "message", T: Timestamp },
  ],
);

/**
 * @generated from message ticketmgr.v1.CreateTicketResponse
 */
export const CreateTicketResponse = /*@__PURE__*/ proto3.makeMessageType(
  "ticketmgr.v1.CreateTicketResponse",
  () => [
    { no: 1, name: "ticket_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message ticketmgr.v1.UpdateTicketRequest
 */
export const UpdateTicketRequest = /*@__PURE__*/ proto3.makeMessageType(
  "ticketmgr.v1.UpdateTicketRequest",
  () => [
    { no: 1, name: "ticket_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "requested_by", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "deadline", kind: "message", T: Timestamp },
  ],
);

/**
 * @generated from message ticketmgr.v1.UpdateTicketResponse
 */
export const UpdateTicketResponse = /*@__PURE__*/ proto3.makeMessageType(
  "ticketmgr.v1.UpdateTicketResponse",
  [],
);

/**
 * @generated from message ticketmgr.v1.DeleteTicketRequest
 */
export const DeleteTicketRequest = /*@__PURE__*/ proto3.makeMessageType(
  "ticketmgr.v1.DeleteTicketRequest",
  () => [
    { no: 1, name: "ticket_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message ticketmgr.v1.DeleteTicketResponse
 */
export const DeleteTicketResponse = /*@__PURE__*/ proto3.makeMessageType(
  "ticketmgr.v1.DeleteTicketResponse",
  [],
);

