// @generated by protoc-gen-es v2.2.3
// @generated from file ticketmgr/v1/service.proto (package ticketmgr.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file ticketmgr/v1/service.proto.
 */
export const file_ticketmgr_v1_service = /*@__PURE__*/
  fileDesc("Chp0aWNrZXRtZ3IvdjEvc2VydmljZS5wcm90bxIMdGlja2V0bWdyLnYxIn0KE0NyZWF0ZVRpY2tldFJlcXVlc3QSFAoMcmVxdWVzdGVkX2J5GAEgASgJEg0KBXRpdGxlGAIgASgJEhMKC2Rlc2NyaXB0aW9uGAMgASgJEiwKCGRlYWRsaW5lGAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCIpChRDcmVhdGVUaWNrZXRSZXNwb25zZRIRCgl0aWNrZXRfaWQYASABKAkitAEKE1VwZGF0ZVRpY2tldFJlcXVlc3QSEQoJdGlja2V0X2lkGAEgASgJEhQKDHJlcXVlc3RlZF9ieRgCIAEoCRISCgV0aXRsZRgDIAEoCUgAiAEBEhgKC2Rlc2NyaXB0aW9uGAQgASgJSAGIAQESLAoIZGVhZGxpbmUYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQggKBl90aXRsZUIOCgxfZGVzY3JpcHRpb24iFgoUVXBkYXRlVGlja2V0UmVzcG9uc2UiKAoTRGVsZXRlVGlja2V0UmVxdWVzdBIRCgl0aWNrZXRfaWQYASABKAkiFgoURGVsZXRlVGlja2V0UmVzcG9uc2UynQIKEFRpY2tldE1nclNlcnZpY2USVwoMQ3JlYXRlVGlja2V0EiEudGlja2V0bWdyLnYxLkNyZWF0ZVRpY2tldFJlcXVlc3QaIi50aWNrZXRtZ3IudjEuQ3JlYXRlVGlja2V0UmVzcG9uc2UiABJXCgxVcGRhdGVUaWNrZXQSIS50aWNrZXRtZ3IudjEuVXBkYXRlVGlja2V0UmVxdWVzdBoiLnRpY2tldG1nci52MS5VcGRhdGVUaWNrZXRSZXNwb25zZSIAElcKDERlbGV0ZVRpY2tldBIhLnRpY2tldG1nci52MS5EZWxldGVUaWNrZXRSZXF1ZXN0GiIudGlja2V0bWdyLnYxLkRlbGV0ZVRpY2tldFJlc3BvbnNlIgBCtQEKEGNvbS50aWNrZXRtZ3IudjFCDFNlcnZpY2VQcm90b1ABWkJnaXRodWIuY29tL3QtYXNoMDQxMC9zdGFjay1leGFtcGxlL2dvL2FwaS90aWNrZXRtZ3IvdjE7dGlja2V0bWdydjGiAgNUWFiqAgxUaWNrZXRtZ3IuVjHKAgxUaWNrZXRtZ3JcVjHiAhhUaWNrZXRtZ3JcVjFcR1BCTWV0YWRhdGHqAg1UaWNrZXRtZ3I6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Describes the message ticketmgr.v1.CreateTicketRequest.
 * Use `create(CreateTicketRequestSchema)` to create a new message.
 */
export const CreateTicketRequestSchema = /*@__PURE__*/
  messageDesc(file_ticketmgr_v1_service, 0);

/**
 * Describes the message ticketmgr.v1.CreateTicketResponse.
 * Use `create(CreateTicketResponseSchema)` to create a new message.
 */
export const CreateTicketResponseSchema = /*@__PURE__*/
  messageDesc(file_ticketmgr_v1_service, 1);

/**
 * Describes the message ticketmgr.v1.UpdateTicketRequest.
 * Use `create(UpdateTicketRequestSchema)` to create a new message.
 */
export const UpdateTicketRequestSchema = /*@__PURE__*/
  messageDesc(file_ticketmgr_v1_service, 2);

/**
 * Describes the message ticketmgr.v1.UpdateTicketResponse.
 * Use `create(UpdateTicketResponseSchema)` to create a new message.
 */
export const UpdateTicketResponseSchema = /*@__PURE__*/
  messageDesc(file_ticketmgr_v1_service, 3);

/**
 * Describes the message ticketmgr.v1.DeleteTicketRequest.
 * Use `create(DeleteTicketRequestSchema)` to create a new message.
 */
export const DeleteTicketRequestSchema = /*@__PURE__*/
  messageDesc(file_ticketmgr_v1_service, 4);

/**
 * Describes the message ticketmgr.v1.DeleteTicketResponse.
 * Use `create(DeleteTicketResponseSchema)` to create a new message.
 */
export const DeleteTicketResponseSchema = /*@__PURE__*/
  messageDesc(file_ticketmgr_v1_service, 5);

/**
 * @generated from service ticketmgr.v1.TicketMgrService
 */
export const TicketMgrService = /*@__PURE__*/
  serviceDesc(file_ticketmgr_v1_service, 0);

