// @generated by protoc-gen-es v2.2.3
// @generated from file ticketmgr/v1/service.proto (package ticketmgr.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file ticketmgr/v1/service.proto.
 */
export declare const file_ticketmgr_v1_service: GenFile;

/**
 * @generated from message ticketmgr.v1.CreateTicketRequest
 */
export declare type CreateTicketRequest = Message<"ticketmgr.v1.CreateTicketRequest"> & {
  /**
   * @generated from field: string requested_by = 1;
   */
  requestedBy: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: google.protobuf.Timestamp deadline = 4;
   */
  deadline?: Timestamp;
};

/**
 * Describes the message ticketmgr.v1.CreateTicketRequest.
 * Use `create(CreateTicketRequestSchema)` to create a new message.
 */
export declare const CreateTicketRequestSchema: GenMessage<CreateTicketRequest>;

/**
 * @generated from message ticketmgr.v1.CreateTicketResponse
 */
export declare type CreateTicketResponse = Message<"ticketmgr.v1.CreateTicketResponse"> & {
  /**
   * @generated from field: string ticket_id = 1;
   */
  ticketId: string;
};

/**
 * Describes the message ticketmgr.v1.CreateTicketResponse.
 * Use `create(CreateTicketResponseSchema)` to create a new message.
 */
export declare const CreateTicketResponseSchema: GenMessage<CreateTicketResponse>;

/**
 * @generated from message ticketmgr.v1.UpdateTicketRequest
 */
export declare type UpdateTicketRequest = Message<"ticketmgr.v1.UpdateTicketRequest"> & {
  /**
   * @generated from field: string ticket_id = 1;
   */
  ticketId: string;

  /**
   * @generated from field: string requested_by = 2;
   */
  requestedBy: string;

  /**
   * @generated from field: optional string title = 3;
   */
  title?: string;

  /**
   * @generated from field: optional string description = 4;
   */
  description?: string;

  /**
   * @generated from field: google.protobuf.Timestamp deadline = 5;
   */
  deadline?: Timestamp;
};

/**
 * Describes the message ticketmgr.v1.UpdateTicketRequest.
 * Use `create(UpdateTicketRequestSchema)` to create a new message.
 */
export declare const UpdateTicketRequestSchema: GenMessage<UpdateTicketRequest>;

/**
 * @generated from message ticketmgr.v1.UpdateTicketResponse
 */
export declare type UpdateTicketResponse = Message<"ticketmgr.v1.UpdateTicketResponse"> & {
};

/**
 * Describes the message ticketmgr.v1.UpdateTicketResponse.
 * Use `create(UpdateTicketResponseSchema)` to create a new message.
 */
export declare const UpdateTicketResponseSchema: GenMessage<UpdateTicketResponse>;

/**
 * @generated from message ticketmgr.v1.DeleteTicketRequest
 */
export declare type DeleteTicketRequest = Message<"ticketmgr.v1.DeleteTicketRequest"> & {
  /**
   * @generated from field: string ticket_id = 1;
   */
  ticketId: string;
};

/**
 * Describes the message ticketmgr.v1.DeleteTicketRequest.
 * Use `create(DeleteTicketRequestSchema)` to create a new message.
 */
export declare const DeleteTicketRequestSchema: GenMessage<DeleteTicketRequest>;

/**
 * @generated from message ticketmgr.v1.DeleteTicketResponse
 */
export declare type DeleteTicketResponse = Message<"ticketmgr.v1.DeleteTicketResponse"> & {
};

/**
 * Describes the message ticketmgr.v1.DeleteTicketResponse.
 * Use `create(DeleteTicketResponseSchema)` to create a new message.
 */
export declare const DeleteTicketResponseSchema: GenMessage<DeleteTicketResponse>;

/**
 * @generated from service ticketmgr.v1.TicketMgrService
 */
export declare const TicketMgrService: GenService<{
  /**
   * @generated from rpc ticketmgr.v1.TicketMgrService.CreateTicket
   */
  createTicket: {
    methodKind: "unary";
    input: typeof CreateTicketRequestSchema;
    output: typeof CreateTicketResponseSchema;
  },
  /**
   * @generated from rpc ticketmgr.v1.TicketMgrService.UpdateTicket
   */
  updateTicket: {
    methodKind: "unary";
    input: typeof UpdateTicketRequestSchema;
    output: typeof UpdateTicketResponseSchema;
  },
  /**
   * @generated from rpc ticketmgr.v1.TicketMgrService.DeleteTicket
   */
  deleteTicket: {
    methodKind: "unary";
    input: typeof DeleteTicketRequestSchema;
    output: typeof DeleteTicketResponseSchema;
  },
}>;

