name: TS/BFF - CI

on:
  pull_request:
    paths:
      - ts/packages/bff/**
      - .github/workflows/ts-bff-ci.yaml
  push:
    branches:
      - master
    paths:
      - ts/packages/bff/**
      - .github/workflows/ts-bff-ci.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ts/packages/bff
    permissions:
      contents: read
    steps:
      - name: Check out codes
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun check

      - name: Test
        run: bun test
