name: TS/Frontend - CI

on:
  pull_request:
    paths:
      - ts/web/packages/frontend/**
      - .github/workflows/ts-frontend-ci.yaml
  push:
    branches:
      - main
    paths:
      - ts/web/packages/frontend/**
      - .github/workflows/ts-frontend-ci.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ts/web/packages/frontend
    permissions:
      contents: read
    steps:
      - name: Check out codes
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Get next cache
        uses: actions/cache@v4
        with:
          path: |
            ts/web/packages/frontend/.next/cache
          key: ${{ runner.os }}-ts-frontend-next

      - name: Lint
        run: bun check
      
      - name: Build
        run: bun run build
